name: 'Ex Flake8 Annotator'
author: 'Exrofol'
description: 'Annotate PRs with flake8 errors and warnings from Github checks output'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'check-circle'
  color: 'green'
