name: Python application

on: [push]

jobs:
  flake8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup flake8 annotations
      uses: ./
    - name: Lint with flake8
      run: |
        pip install flake8 pep8-naming flake8-annotations
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./violations.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

